[package]
name = "http-sample"
version = "0.1.0"
edition = "2024"

# [package.metadata.namui]
# targets = [
#     "x86_64-pc-windows-msvc",
#     "x86_64-unknown-linux-gnu",
#     "wasm32-wasi-web",
#     "aarch64-apple-darwin",
# ]

[dependencies]
namui = { path = "../../namui" }
namui-prebuilt = { path = "../../namui-prebuilt" }
